### ISSUE TITLE
Unable to locate request-reviewers.yml

### ISSUE THREAD

**Issue by YoavGro** [neo-diego-beltran/request-reviewers#1]
I'm trying to run the action but get this error 

`Warning: Unexpected input(s) 'GITHUB_TOKEN', 'config_path', valid inputs are ['who-to-greet']
Run neo-diego-beltran/request-reviewers@f0[2](https://github.com/riversidefm/mobile-test/actions/runs/3881189619/jobs/6619925154#step:2:2)8[3](https://github.com/riversidefm/mobile-test/actions/runs/3881189619/jobs/6619925154#step:2:3)75d516d93d6a4dd5f93feccfc7f3c768a9b
  with:
    GITHUB_TOKEN: ***
    config_path: .github/request-reviewers.yml
    who-to-greet: World
Repository owner: riversidefm

Repository name: mobile-test

Could not get the content from content path .github/request-reviewers.yml ERROR: HttpError: Not Found

Could not get the content from content path .github/CODEOWNERS ERROR: HttpError: Not Found

Current PR number: 1

Current PR labels: Studio

Current PR author: YoavGro

Current PR CODEOWNERS: 

Current PR reviewers To Remove: YoavGro

Current PR teams assignees: 

Current PR individuals assignees:`

**Comment by YoavGro** [comment]
The .github/request-reviewers.yml
Has the config file as the docs say

**Comment by neo-diego-beltran** [comment]
hey, you can try setting your with section with the following code example

```yml
with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      config_path: '.github/request-reviewers.yml'
      codeowners_path: '.github/CODEOWNERS' <- this path is not required but the file needs to be there
```
